services:

  java:
    build:
      context: ./java/selenium/
      dockerfile: ./Dockerfile
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"

volumes:
  chrome_profiles: