apiVersion: v1
kind: Service
metadata:
  name: microservice-java
  labels:
    app: microservice-java
spec:
  selector:
    app: microservice-java
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
